### ISSUE TITLE
FSLeyes automatically applies spline interpolation when opening 3D view

### ISSUE THREAD

**Issue by thewilliamdrew** [pauldmccarthy/fsleyes#103]
Hello!

After updating FSLeyes, I have come across a behavior that I think is new. When ever I open a 3D view, it automatically applies spline interpolation (from no interpolation) to all views. Is this expected? Is there a way to disable this behavior?

Thanks!

**Comment by pauldmccarthy** [comment]
Hi @thewilliamdrew, this was an intentional change I made to improve the default display settings for 3D views. Unfortunately there is no way to decouple the interpolation setting across views, so enabling it for a 3D view will enable it for the ortho (and other) views.

If this is a real problem for you, it would be trivial for me to add a command-line flag to disable the new behaviour (e.g. `fsleyes --no_3d_interp` or something).

**Comment by thewilliamdrew** [comment]
That would be greatly appreciated! Thank you so much! I've been puzzling over this for weeks. 

Might I recommend a new feature (I don't think this exists yet) to have a user settable "config file" that would apply some settings/command-line flags every time FSLeyes is started? This would make setting some routine configurations much easier (e.g. not having to remember to set `--neuroOrientation` or `--fontSize` or the new `--no_3d_interp` that you have proposed).

Thank you again for your quick response!

**Comment by pauldmccarthy** [comment]
That's easily done - in the next version you'll be able to store any arguments you would always like to have applied in `<fsleyes-settings-dir>/default_arguments.txt` (where `<fsleyes-settings-dir>` is typically `~/.fsleyes/` on macOS, or `~/.config/fsleyes/` on Linux/WSL).

**Comment by thewilliamdrew** [comment]
Amazing! Thanks a bunch!
