### ISSUE TITLE
Problem with install on M3 macOS

### ISSUE THREAD

**Issue by plbenveniste** [pauldmccarthy/fsleyes#133]
Hello ! 
Opening this issue to raise a problem I encountered. 
When I tried installing fsleyes with the method `python fslinstaller.py` I ran into the following issue:
```console
/Users/plbenveniste/fsl/bin/mamba env update -p /Users/plbenveniste/fsl -f /private/var/folders/_2/l62mvrbx76l6nx_408gf05140000gn/T/tmpx5ub9wd7/fsl-6.0.7.7_macos-M1.yml
```

This is very likely because my computer runs on macos-M3. 

However, the installation was successful when using `conda install -c conda-forge fsleyes`.

**Comment by pauldmccarthy** [comment]
Hi @plbenveniste, this repository is specifically for FSLeyes issues - for FSL issues, the [FSL mailing list](https://fsl.fmrib.ox.ac.uk/fsl/docs/#/support) is the place to ask questions.

Having said this, I suspect that your FSL installation will work if you run the fslinstaller with the `--miniconda` option, e.g.:

```
python fslinstaller.py --miniconda https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh
```

We have fixed this issue for the next version of FSL, which is due to be released very soon.
