### ISSUE TITLE
Scaling Problem with resampled CT

### ISSUE THREAD

**Issue by nfocke** [pauldmccarthy/fsleyes#25]
I am running into problems with color-scaling a resampled CT scan (sampled to 0.5mm iso and rigid-aliged to MNI space with FLIRT). See the attached screenshots for details:
fsleyes1: broad window (-200 : 2000), resampled image
fsleyes2: tight window (20 : 80), resampled image
fsleyes3: broad window (-200 : 2000), original image
fsleyes4: tight window (20 : 80), origial image

The upsampled image is displayed as expected with fslview, see attached:
fslview1: broad window (-200 : 2000), resampled image
fslview2: tight window (20 : 80), resampled image

[FSLeyes_scaling_problem.zip](https://github.com/pauldmccarthy/fsleyes/files/3281382/FSLeyes_scaling_problem.zip)

It seems there is a problem with HU/intesnity crossing 0 in the image. The dynamic range seems to be somehow clipped shortly after the "min" value. An MRI image sampled the same way (same resolutiona and space) is displayed fine. Since fslview displays just fine, it seems to be not a problem with the image. Also, the intensities shown in the coordinates field, ar as expected. So, it seems to be a pure visual problem, the data points themselfs seem the have the correct intensities. Why this happens after the FLIRT resampling (spline interp.) and just for CT, I have no clues, unless the negative HU present in CT.

I used both fslyese 0.29 and 0.27., with the same issue.

Any ideas?

**Comment by pauldmccarthy** [comment]
Hey @nfocke, I wouldn't be able to tell for sure without knowing a bit more about your platform (output of `glxinfo`), and the data (data type, and minimum/maximum values).

However, my guess is that:
1. You are using FSLeyes over SSH, or within a VNC session
2. The image contains some extremely small or large values

When running in a remote/limited environment, floating point images need to be converted into `uint16` due to OpenGL limitations. This means that, for images with an extremely large range, the interesting data will be squashed to take up a very small part of the possible data range, which will result in weird behaviour like this.

A work around is to tell FSLeyes to ignore the actual data range by using the `--overrideDataRange`/`-or` option, e.g.:

```
fsleyes image.nii.gz -or -200 2000
```

**Comment by nfocke** [comment]
Dear Paul,

 

yes, in deed. I run fslyes in a xrdp scenario (on a Centos 7 box).

 

The –or option made the image displayable, but did not allow for changing the scaling on the fly naturally.

The datatype was “doube”, seemingly the default of flirt in spline interpolation. When changing it to “int”/INT32 with fslmaths display was back to normal.

 

So, my issue is solved in this regard, but maybe a more general solution would be possible? When the –or is manually set (and the window is chosen equally) it looks okay. So if the range was automatically adopted to the entered Min/Max this would probably work? Otherwise, at least some warning message in this case might save you some emails…;)

 

Interestingly the old fslview could handle the same image (in the same xrdp environment) just fine. Probably since this is not OpenGL based?

 

Anyways, many thanks for your quick response and solution. 

 

All the best,


Niels

 

 

 

Von: Paul McCarthy [mailto:notifications@github.com] 
Gesendet: Mittwoch, 12. Juni 2019 15:32
An: pauldmccarthy/fsleyes <fsleyes@noreply.github.com>
Cc: nfocke <niels.focke@uni-tuebingen.de>; Mention <mention@noreply.github.com>
Betreff: Re: [pauldmccarthy/fsleyes] Scaling Problem with resampled CT (#25)

 

Hey @nfocke <https://github.com/nfocke> , I wouldn't be able to tell for sure without knowing a bit more about your platform (output of glxinfo), and the data (data type, and minimum/maximum values).

However, my guess is that:

1.	You are using FSLeyes over SSH, or within a VNC session
2.	The image contains some extremely small or large values

When running in a remote/limited environment, floating point images need to be converted into uint16 due to OpenGL limitations. This means that, for images with an extremely large range, the interesting data will be squashed to take up a very small part of the possible data range, which will result in weird behaviour like this.

A work around is to tell FSLeyes to ignore the actual data range by using the --overrideDataRange/-or option, e.g.:

fsleyes image.nii.gz -or -200 2000

**Comment by pauldmccarthy** [comment]
The problem is caused by the presence of extreme outliers in your image file (and that running OpenGL over a network is subject to various limitations). All you need to do is set the override range such that FSLeyes will ignore those outliers. The exact values to use will depend on your data. 

Once you have enabled the range override option, you should then be able to adjust the brightness/contrast/min/max on the fly as normal.

So this *is* the solution. It is not feasible to automatically adjust the override range on the fly every time you change the min/max, because this would require re-scaling the data and re-copying it to the graphics card every time the min/max/brightness/contrast get adjusted, which would kill performance. 

Currently, FSLeyes will automatically enable the override range for images which have a data range greater than 10<sup>7</sup> - for images with a data range greater than this, it will set the override range override such that voxels outside the 1st or 99th percentiles will be ignored.

But it is evidently not being automatically enabled for your data. Would you be able to share the problematic image with me? Or at least give me the output of `fslinfo image.nii.gz`, and `fslstats image.nii.gz -R`?

And yes - FSLView only uses OpenGL for the 3D view, whereas FSLeyes uses OpenGL for both 2D and 3D rendering. This comes with the advantage of being able to display more complicated scenes, but has the drawback of being somewhat limited when running on a remote server.

**Comment by nfocke** [comment]
Dear Paul,

 

see the link below. It is a fairly large dataset (since sampled to 0.5mm iso).

 

 <https://owncloud.gwdg.de/index.php/s/AmsXnuJYHQFl5qB> https://owncloud.gwdg.de/index.php/s/AmsXnuJYHQFl5qB

 

 

ATB,

 

Niels

 

Von: Paul McCarthy [mailto:notifications@github.com] 
Gesendet: Donnerstag, 13. Juni 2019 02:17
An: pauldmccarthy/fsleyes <fsleyes@noreply.github.com>
Cc: nfocke <niels.focke@uni-tuebingen.de>; Mention <mention@noreply.github.com>
Betreff: Re: [pauldmccarthy/fsleyes] Scaling Problem with resampled CT (#25)

 

The problem is caused by the presence of extreme outliers in your image file (and that running OpenGL over a network is subject to various limitations). All you need to do is set the override range such that FSLeyes will ignore those outliers. The exact values to use will depend on your data.

Once you have enabled the range override option, you should then be able to adjust the brightness/contrast/min/max on the fly as normal.

So this is the solution. It is not feasible to automatically adjust the override range on the fly every time you change the min/max, because this would require re-scaling the data and re-copying it to the graphics card every time the min/max/brightness/contrast get adjusted, which would kill performance.

Currently, FSLeyes will automatically enable the override range for images which have a data range greater than 107 - for images with a data range greater than this, it will set the override range override such that voxels outside the 1st or 99th percentiles will be ignored.

But it is evidently not being automatically enabled for your data. Would you be able to share the problematic image with me? Or at least give me the output of fslinfo image.nii.gz, and fslstats image.nii.gz -R?

And yes - FSLView only uses OpenGL for the 3D view, whereas FSLeyes uses OpenGL for both 2D and 3D rendering. This comes with the advantage of being able to display more complicated scenes, but has the drawback of being somewhat limited when running on a remote server.

**Comment by pauldmccarthy** [comment]
So your image has a data range of [-1545.4, 3402.8], but all of the useful data is in the range [-120, 120]. 
The

**Comment by nfocke** [comment]
Okay. I guess the extreme values ar due to the spline interpolation applied during registration of the image. Since this is CT, we have a-priori a clear idea of which HU range we are looking for, so could either threshold accordingly or use the -ot option. 
Thanks for investigating.
