### ISSUE TITLE
Unable to launch of space in application name

### ISSUE THREAD

**Issue by neurolabusc** [pauldmccarthy/fsleyes#3]
FSLeyes 0.24.6 on MacOS 10.13.6. The application works fine if you name it "FSLeyes.app" or "FSLeyes2.app", but fails to launch if there is a space in the name" "FSLeye 2.app". This would seem to be a rare occurrence, but in my case when I extracted the zip download the OS noticed I had an older copy in the same location and automatically appended " 2" to the filename.

**Comment by pauldmccarthy** [comment]
Hey @neurolabusc thanks for the report! This is caused by a lack of quoting in a [hacky wrapper script](https://git.fmrib.ox.ac.uk/fsl/fsleyes/build/blob/master/entrypt.sh) I introduced recently to absorb some debug messages that I have no control over.

I'm literally about to do a new release, so this should be resolved for 0.25.0.

**Comment by pauldmccarthy** [comment]
n.b. The link in my previous comment refers to the current, fixed, version of the script.

**Comment by pauldmccarthy** [comment]
Hi @neurolabusc, FSLeyes 0.25.0 is [available for download](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FSLeyes) - would you mind checking that this problem has been fixed? Thanks!
