### ISSUE TITLE
timeseries plot lines are not visible different to colorblind people

### ISSUE THREAD

**Issue by poldrack** [pauldmccarthy/fsleyes#52]
When I plot several timeseries next to one another, I am not able to visually distinguish between the different lines (in this example, the lines for test_stopSignal_go and test_stopSignal_stop_success) because of color vision problems. it would be helpful to distinguish by pattern as well - failing that, perhaps you could use a colorblind-friendly pallette?
![screenshot](https://user-images.githubusercontent.com/871056/85301230-6e600980-b45c-11ea-9c20-dc2b54f9b1b6.png)

**Comment by pauldmccarthy** [comment]
Hi @poldrack, this is a good point - I have to confess that I had not considered good default colours for all users. Note that it is possible to change the line colour and style for individual series, but I think it makes sense to have more accessible default values.

Do you think something like the schemes outlined under *Qualitative colour schemes* at the link below would be a good default?

https://personal.sron.nl/~pault/

It seems that the ability to "parameterise" line styles has been added to matplotlib since I last checked, so perhaps it would be a good idea to vary the style for e.g. the first 6 series added to a plot.

https://matplotlib.org/gallery/lines_bars_and_markers/linestyles.html

**Comment by poldrack** [comment]
thanks! I didn't see a way to change the line color/style, but I think I am working with a fairly old version.
I like those color schemes - but I also think that varying style would help too.

**Comment by pauldmccarthy** [comment]
You should be able to change the colour/style for the currently selected overlay via the plot control panel (the spanner button on the plot view panel toolbar). Or, if you have "held" the time series for a particular voxel, that series will be added to the plot list, where you can change its display settings:

https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/userdoc/latest/plot_views.html#holding-data-series-and-the-plot-list

The interface may be different for you, depending on the vintage of your installed version of FSLeyes.

In any case, I was planning to release a new bugfix version tomorrow, so should be able to sneak in this change.

**Comment by pauldmccarthy** [comment]
How about this for the default pallete/style? I also bumped up the default width, as I've always preferred the lines a bit thicker.

![screenshot](https://user-images.githubusercontent.com/236128/85335195-81aebb80-b4d4-11ea-9bc8-628b16188455.png)

**Comment by poldrack** [comment]
looks great to me!

**Comment by pauldmccarthy** [comment]
FSLeyes 0.33.2 has these adjusted default settings - feel free to re-open this issue if you think they could be improved upon.
