### ISSUE TITLE
Impossible to use fsleyes from conda install (Ubuntu 20.04)

### ISSUE THREAD

**Issue by mick-d** [pauldmccarthy/fsleyes#57]
I get the same `Index must be completely built in order to seek from SEEK_END` errors when trying to open any volume (including standard atlases) after a fresh install of `fsleyes`. This might be due to a problem with `nibabel` as reported [here](https://github.com/pauldmccarthy/indexed_gzip/issues/38).

I tried to install `fsleyes` with `conda` using three different python versions (`3.6`, `3.7` and `3.8`), each time in a new conda environment fetching packages from the conda-forge channel. But each time I get the same error when trying to open files.

In the end i had to use `pip` as it turned out impossible to have a working version of `fsleyes` with `conda`. Any help for future conda installations would be very useful.

**Comment by pauldmccarthy** [comment]
Hi @mick-d, this is a problem with both `nibabel` and `indexed_gzip`.  `nibabel` has been fixed, but is not yet available on `conda-forge` - it can take a few days for releases to propagate to there. In the meantime, if you install the latest `nibabel` via `pip`, you should be able to avoid the error.

This error has also bveen fixed in `indexed_gzip`, but there is another [related `indexed_gzip` issue](https://github.com/pauldmccarthy/indexed_gzip/issues/40) which I will be releasing a patch for shortly. Although this second issue will only cause issues when trying to load very small images (less than a few MB uncompressed).

**Comment by effigies** [comment]
Ah, apologies. I failed to push the nibabel 3.1.1 tag to GitHub, so the conda-forge feedstock isn't getting updated. I need to get to my other machine to push that, but expect it today.

**Comment by effigies** [comment]
nibabel 3.1.1 is up on conda-forge.

**Comment by pauldmccarthy** [comment]
thanks @effigies!

@mick-d could you try upgrading `nibabel` in your conda environment, to see if that fixes FSLeyes?

**Comment by mick-d** [comment]
@pauldmccarthy @effigies I can confirm i had `nibabel            conda-forge/noarch::nibabel-3.1.0-py_0` in previous (not working) environment, and after a fresh install today, i have `nibabel            conda-forge/noarch::nibabel-3.1.1-py_0` installed from `conda-forge` in the new environment.

`fsleyes` is now working fine with a fresh `conda` install. 

Thanks a lot for the amazingly quick feedback!
