### ISSUE TITLE
FSLeyes just exits on launch

### ISSUE THREAD

**Issue by dmd** [pauldmccarthy/fsleyes#58]
I'm real puzzled, because this was working fine a few days ago, and I don't know of anything that changed.

```
$ echo $FSLDIR
/cm/shared/fsl-6.0.3
$ $FSLDIR/bin/fsleyes

$ echo $? 
1
```

That's it, that's all I get. It just exits immediately. No splash screen, no errors. Other X11 apps run fine. 

Attached the results of `strace $FSLDIR/bin/fsleyes`, if that helps. It *claims* to be writing some stuff to stderr, but... where'd it go?

[strace.txt](https://github.com/pauldmccarthy/fsleyes/files/4854800/strace.txt)

**Comment by dmd** [comment]
Completely wiping and reinstalling FSL 6.0.3 solved this, so I suspect one of the operations we did in #53 was to blame.

**Comment by pauldmccarthy** [comment]
Continuing from the conversation over at #53, looking at that strace output, my guess is that it is actually hitting the same `indexed_gzip` `SEEK_END` problem, which should be resolved by upgrading nibabel and/or indexed_gzip. 

Again guessing, but I'm going to postulate that the difficulty you've been having in getting a consistent up-to-date `fslpython` environmenmt is due to the fact that the environment specification [is broken](https://github.com/pauldmccarthy/fsleyes/issues/53#issuecomment-656219680). There should be a new version of FSL out in the next week or two, in which we've hopefully ironed out these issues.

**Comment by pauldmccarthy** [comment]
Closing - see https://github.com/pauldmccarthy/fsleyes/issues/53#issuecomment-658206347
