### ISSUE TITLE
Installing on MacOS Big Sur (10.16)

### ISSUE THREAD

**Issue by ahill187** [pauldmccarthy/fsleyes#70]
## Operating System/Environment

OS: MacOSX Big Sur (10.16)

## Issue

If you do not install `FSL`, and try to install just `fsleyes` standalone:
```
conda install -c conda-forge fsleyes
```
it will not install.

If you first install `FSL`, you have to select ``Catalina (10.15)`` for the download, and the install of `FSL` works.
However, if you then go to install `fsleyes`:
```
conda install -c conda-forge fsleyes
```
it will install, but fail to open.

## Workaround

As mentioned here: https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=FSL;8ee55ea9.2011

If you install `FSL`, and then `fsleyes`, as described above, you can edit the source code to get it to open:

Use a text editor to open the ``ctypesloader.py`` file:

```
    atom ${FSLDIR}/fslpython/envs/fslpython/lib/python3.x/site-packages/OpenGL/platform/ctypesloader.py
```

Search for the following line:

```
    fullName = util.find_library( name )
```
Comment this line out and add these 4 lines:

```
    # fullName = util.find_library( name )
    if name == "OpenGL":
      fullName = "/System/Library/Frameworks/OpenGL.framework/OpenGL"
    elif name == "GLUT":
      fullName = "/System/Library/Frameworks/GLUT.framework/GLUT"
```

**Comment by pauldmccarthy** [comment]
Thanks; this should already be fixed in the latest version of FSLeyes - what do you mean when you say that _it will not install_, when installing directly through conda?

The version of FSLeyes which is installed for a particular version of FSL is fixed, so for the current version of FSL you will get a slightly older version of FSLeyes. But, after installing FSL, you should be able to upgrade to the latest version of FSLeyes to work around this issue, without modifying the code (although there is a [completely unrelated issue on macOS](https://github.com/conda-forge/wxpython-feedstock/issues/70) which you will probably run into).

**Comment by ahill187** [comment]
I forget what the error was for `FSLeyes` not installing without `FSL` first; I'll uninstall and try again from scratch and I can give you the error message.

**Comment by ahill187** [comment]
Okay, well it seems to be working now! I'm not sure what the issue was before, perhaps the environment was set up incorrectly.

**Comment by pauldmccarthy** [comment]
If FSLeyes did originally install, but then crashed when you tried to run it, my guess is the [issue with the wxPython conda-forge package](https://github.com/conda-forge/wxpython-feedstock/issues/70) which was resolved after you originally opened this issue, but before your second attempt.
