### ISSUE TITLE
Ability to force images in same scaled voxels space even if sform/qform differ (slightly)

### ISSUE THREAD

**Issue by ibrwr** [pauldmccarthy/fsleyes#84]
Sometimes I want to view images that I know are conceptually in the same space but that have some (small) differences in the qform/sform (usually because the software that produced them apparently did not set the headers correctly. 

It is very useful that fsleyes clearly points out that the headers do not show alignment ('Displaying images with different orientations/field of view'). I am assuming that in this case fsleyes will actually interpolate the images that have a different sform/qform from the reference image. It would be very handy to see with a press of a button (or command line option) how the images look when they all use the same scaled voxels space of the reference image. I realize I can achieve this by applying fslcpgeom on those images before I load them, but the convenience of being able to view them that way in fsleyes without having to preprocess the images would really be great in my opinion. 

Thanks for making this great software available!

**Comment by pauldmccarthy** [comment]
Hi @ibrwr, this was actually available in an early (pre-release) version of FSLeyes - I had originally envisaged the *Display space* option (in the view settings panel - the spanner button) to allow the user to choose between raw voxels, scaled voxels, a reference image, or world coordinates. But the first two options were deemed unnecessary / too complicated, so were removed. 

I did, however, leave in a hook though, to project all images into the scaled voxel space, with the origin fixed at the corner of voxel (0, 0, 0) (read more about the FSL / FSLeyes scaled voxel coordinate system [here](https://open.win.ox.ac.uk/pages/fsl/fsleyes/fsleyes/userdoc/display_space.html#reference-image-space)). You can enable this by opening the _Views -> Python shell_, and executing the `scaledVoxels()` function.

Note though that this feature is not supported very well, and that many operations (e.g. opening a second ortho view) will force the display space to be reset.

I will try and find time to look through the code, to see how easy it is to add scaled voxels back in as a first-class option.

**Comment by pauldmccarthy** [comment]
Hi @ibrwr, I've added *Scaled voxel coordinates* as an option for the display space setting in FSLeyes 1.2.0, if you'd like to try it out. 

The origin, shared by all images, is at the **centre** of voxel `(0, 0, 0)`, rather than the corner. It would be possible to change this to be the corner, but would require a bit more work (there is some code which is tightly coupled to using the centre as origin), and I figured that using the centre was probably good enough for most needs.

**Comment by ibrwr** [comment]
Thanks @pauldmccarthy! Really great to have this feature! We are going to try it out. Some first test feedback about two small things I noticed: 
 --displaySpace scaledVoxel is a command line option but is not mentioned in the help file yet
* Below the images it says 'Coordinates: Aligned anatomical' which is probably not correct when this option is selected

Again, thanks so much for implementing this!

**Comment by pauldmccarthy** [comment]
Hi @ibrwr 

> It would be great to have the anatomical labels (LR etc.) instead of Xmin Xmax etc.

The problem with this is that the labels would only be relevant for the currently selected overlay, as different overlays potentially have different voxel orientations. So having L/R etc would potentially be misleading if you had one overlay selected, but were looking at a different overlay in a different orientation. I'm not sure whether this would be a good idea.

> Below the images it says 'Coordinates: Aligned anatomical' which is probably not correct when this option is selected

That label comes from the NIFTI header of the currently selected image, and refers to the space in which the mm coordinates that are listed just below are defined. If you were viewing a MNI152 image, it would say *Coordinates: MNI152*

**Comment by ibrwr** [comment]
Hi @pauldmccarthy 

Thank you for the clarification. 

> > It would be great to have the anatomical labels (LR etc.) instead of Xmin Xmax etc.
> 
> The problem with this is that the labels would only be relevant for the currently selected overlay, as different overlays potentially have different voxel orientations. So having L/R etc would potentially be misleading if you had one overlay selected, but were looking at a different overlay in a different orientation. I'm not sure whether this would be a good idea.
> 
That is a very good point. Would it be even better if it would show XMin etc. in case the orientations (LAS vs RAS etc. ) are not the same for all images in the stack, but that it would show LR etc. labels if they are all the same, or even ideally, if all images that have visibility turned on are the same so you could even quickly switch on and off certain images to see which is the one with the different orientation? I hope you don't mind me brainstorming out loud what further enhancements could be made. Having the scaledvoxels feature is great!

**Comment by ibrwr** [comment]
I actually realize now that I probably misunderstand something. When I create a LAS duplicate of a RAS nifti (fslorient -forceradiological followed by swapdim -x) and open both the RAS and LAS version at the same time in fsleyes with scaled voxels, they do appear identical similar to how they would appear in fslview. So even if the storage order of different overlays are different, the orientation information in the header is used to display them in the same way, e.g. right side on the 'R' side. So I would think that labels could be displayed with LR etc. as in fslview, but i'm probably overlooking something?

**Comment by pauldmccarthy** [comment]
@ibrwr Actually, I've just realised that I've made a mistake - the L/R flip shouldn't be taking place at all when images are being viewed in this scaled voxel coordinate system - the `Xmin` / `Xmax` etc labels are actually incorrect when viewing images with different storage orders (e.g. overlaying a L->R image on top of a R->L image).

the entire point of this feature (for me, originally) was so I could see images in the way they are stored in the file (i.e. with their voxel storage order), so that they are all aligned via an origin at voxel coordinate (0, 0, 0).

But regarding the discussion around anatomical labels, when the L/R flip is applied, it still isn't possible to assume consistent anatomical orientation across multiple images,  as that would be assuming that the first voxel axis maps to L-R, which is not necessarily the case. The flip is always applied to the *first* voxel axis, regardless of whether it actually corresponds to L-R, and is a historical relic within FSL - it is applied in the internal coordinate system used by many FSL tools, described [here](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FLIRT/FAQ#What_is_the_format_of_the_matrix_used_by_FLIRT.2C_and_how_does_it_relate_to_the_transformation_parameters.3F). 

This coordinate system was devised when ANALYZE was still in widespread use - the ANALYZE format does not contain any orientation information, and so the voxel storage order is always assumed to be RL AP IS (I'm not considering negative pixdims, but that is irrelevant for this discussion). The L/R flip in the internal FSL coordinate system, and in FSLeyes, is a hack to try and ensure that the L/R handedness of different images is always consistent. But this all breaks down when presented with an image for which the first voxel axis does not correspond to L/R (which are not that uncommon, in my experience).  When viewing NIFTI images, the L/R flip is entirely unnecessary, as the NIFTI standard mandates that the voxel-to-world affine stored in an image header must project the image data into a RAS coordinate system.

So in this scaled voxel coordinate system, the only information which is guaranteed to be consistent across all images is the voxel storage order/direction (well, it would be, if I hadn't made the mistake of applying the flip).
